### ISSUE TITLE
unexpected keyword `timeout` during first login attempt

### ISSUE THREAD

**Issue by jeremygray** [psychopy/pyosf#1]
Trying to login in from PsychoPy project menu, the dialog comes up. I entered my info, checked 'remember me'.

```
Traceback (most recent call last):
  File "/Users/jgray/code/psychopy/psychopy/app/projects.py", line 266, in onLogin
    password=pword, remember_me=rememberMe)
  File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyosf/remote.py", line 233, in __init__
    self.authenticate(username, password, otp)
  File "/Users/jgray/anaconda/lib/python2.7/site-packages/pyosf/remote.py", line 400, in authenticate
    otp_val = resp.headers.get('X-OSF-OTP', '', timeout=5.0)
TypeError: get() got an unexpected keyword argument 'timeout'
```

**Comment by peircej** [comment]
Ah. You've got 2FA set up for your OSF account (I haven't) and this line 
hadn't been tested.
The timeout argument needs removing but I'll also need to implement 
something to get/send the 2FA auth code (or `otp` as it appars in that code)

On 30/03/2016 12:56, Jeremy R. Gray wrote:
>
> Trying to login in from PsychoPy project menu, the dialog comes up. I 
> entered my info, checked 'remember me'.
>
> |Traceback (most recent call last): File 
> "/Users/jgray/code/psychopy/psychopy/app/projects.py", line 266, in 
> onLogin password=pword, remember_me=rememberMe) File 
> "/Users/jgray/anaconda/lib/python2.7/site-packages/pyosf/remote.py", 
> line 233, in __init__ self.authenticate(username, password, otp) File 
> "/Users/jgray/anaconda/lib/python2.7/site-packages/pyosf/remote.py", 
> line 400, in authenticate otp_val = resp.headers.get('X-OSF-OTP', '', 
> timeout=5.0) TypeError: get() got an unexpected keyword argument 
> 'timeout' |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/pyosf/issues/1>
>

-- 
Jonathan Peirce
Nottingham Visual Neuroscience

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.
